disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Roar"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2026"
description = "Roar website."

[params.author]
name = "Jonathan Dan"
